### ISSUE TITLE
does ur iStatMenu works good on cpu temprature and fans with 9700k?

### ISSUE THREAD

**Issue by bjrjustin** [wellsgz/Opencore-Gigabyte-Z390M-Gaming-Hackintosh#1]

**Comment by bjrjustin** [comment]
mine is 8700k, isStatMenu doesn't show up temperature and fans and fan speed control,but hwmontiorsmc2 works well

**Comment by wellsgz** [comment]
> mine is 8700k, isStatMenu doesn't show up temperature and fans and fan speed control,but hwmontiorsmc2 works well

with iStatMenu helper installed, CPU temperature works fine in my setup (GPU temperature is blank)

**Comment by Pain-and-Love** [comment]
> mine is 8700k, isStatMenu doesn't show up temperature and fans and fan speed control,but hwmontiorsmc2 works well

9900ks.  with the same questions.    no temp in the  iStatMenu
