### ISSUE TITLE
PM sleep and awake problem

### ISSUE THREAD

**Issue by bjrjustin** [wellsgz/Opencore-Gigabyte-Z390M-Gaming-Hackintosh#2]
the machine sleeps pretty good, when it sleep, the fans stop and all light turned off. But when it wakes up, Chrome and some other softwares would crash and no responding.
`log show --last 1d | grep "Wake reason"`
![image](https://user-images.githubusercontent.com/24447340/75215108-ab780000-57ca-11ea-8930-1aa7a9ae8a39.png)

**Comment by wellsgz** [comment]
> the machine sleeps pretty good, when it sleep, the fans stop and all light turned off. But when it wakes up, Chrome and some other softwares would crash and no responding.
> `log show --last 1d | grep "Wake reason"`
> ![image](https://user-images.githubusercontent.com/24447340/75215108-ab780000-57ca-11ea-8930-1aa7a9ae8a39.png)

It seems no configuration can be made to tweak this, I think we will need to wait for upstream OpenCore update.
